apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic-search
  name: apm-server-config
  labels:
    app: apm-server

data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      rum:
        enabled: true
        event_rate.limit: 300
        event_rate.lru_size: 1000
        allow_origins: ['*']
        library_pattern: "node_modules|bower_components|~"
        exclude_from_grouping: "^/webpack"
        source_mapping.enabled: true
        source_mapping.cache.expiration: 5m
        source_mapping.index_pattern: "apm-*-sourcemap*"
      frontend:
        enabled: false
    setup.template.settings:
      index:
        number_of_shards: 1
        codec: best_compression
    output.elasticsearch:
      hosts: "http://elasticsearch-svc:9200"
    setup.kibana:
      host: "http://kibana-svc:9200"
