apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic-search
  name: apm-server-config
  labels:
    app: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"

    output.elasticsearch:
      hosts: "elasticsearch-svc.elastic-search.svc.cluster.local:9200"

    setup.kibana:
      host: "kibana-svc.elastic-search.svc.cluster.local:5601"  
